Content:
    cardinal:
        root_dir: doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Cardinal
        repo: https://github.com/neams-th-coe/cardinal
        menu:
            Getting Started:
                Installing Cardinal: start.md
                How to Contribute: contributing.md
            Documentation:
                Tutorials: tutorials/index.md
                Input Syntax: source/index.md
                CFD Meshing: tutorials/meshing.md
                Code Theory: theory/index.md
                Running on HPC: hpc.md
                Doxygen: doxygen.md
            Status:
                SQA: sqa/index.md
            Publications: publications.md
            Contact: contact.md
            Help: faq.md
            News: news.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
        active: true
    MooseDocs.extensions.template:
        active: true
    MooseDocs.extensions.algorithm:
        active: true
    MooseDocs.extensions.sqa:
        active: True
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        categories:
            cardinal: !include ${ROOT_DIR}/doc/sqa_cardinal.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
    MooseDocs.extensions.acronym:
        acronyms:
            moose: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
            vtb: !include ${ROOT_DIR}/doc/acronyms.yml
    MooseDocs.extensions.analytics:
        active: True
        google_measurement_id: G-FDCX1GZ9HF
